# -*- coding: utf-8 -*-
"""pattern fatching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeZoRao1iZ8BmVuss8FHEAYnuSTqwbSJ
"""

# from flask import Flask, request, render_template
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
import warnings
import os
import time

# Suppress warnings
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None

def calculate_ema(df, period):
    """
    Calculate Exponential Moving Average (EMA) for a given period.
    Returns None if insufficient data.
    """
    if len(df) < period:
        return None
    return df['Close'].ewm(span=period, adjust=False).mean()

def poles(data):
  # Returns a list of integer indices where the close price increased by more than 7% from the previous day's close.
  final_result = []
  for i in range(1,len(data)):
    if ((data['Close'].iloc[i].item()) - data['Close'].iloc[i-1].item()) / data['Close'].iloc[i-1].item() > 0.07:
      final_result.append(i)
  return final_result

def flag(data):
  result = []
  c_poles = poles(data)
  for pole_i in c_poles:
    # print(pole_i)
    flag = 0
    pole_high = data['High'].iloc[pole_i].item()
    pole_close = data['Close'].iloc[pole_i].item()
    pole_open = data['Open'].iloc[pole_i].item()
    pole_low = data['Low'].iloc[pole_i].item()
    # pole_half = round((pole_close - pole_open)/2,2) + pole_open #1
    price_diff = round((pole_high - pole_low),2) #1
    pole_618 = round(pole_high - (price_diff*0.618),2) #1
    if pole_i+7 >= len(data):
      continue
    else:
      for i in range(pole_i+1, pole_i+8):
        if i >= len(data):
          continue
        flag_close = data['Close'].iloc[i].item()
        flag_low = data['Low'].iloc[i].item()

        flag_09ema = data['09_ema'].iloc[i]
        flag_20ema = data['20_ema'].iloc[i]

        # If EMA is NaN, it's not a valid flag condition
        if pd.isna(flag_09ema) or pd.isna(flag_20ema):
            break

        if flag_close > pole_high or flag_close < pole_618 or flag_close < flag_09ema or flag_close < flag_20ema:   # or flag_low < pole_half
          # print(f"{pole_high}  false for {flag_close}---------"" {i})
          break
        else:
          flag+=1
          if flag > 6:
            result.append({
                'ticker name' : data.columns[0][1].split('.')[0],
                'start index' : data.index[pole_i].date(),
                'end index' : data.index[pole_i + flag].date(),
                'price' : data['Close'].iloc[-1].item()
            })
          # print(f"{flag} for {pole_i}")

  return result

def index():
  all_results = []
  # symbol_name_csv = pd.read_csv('EQUITY_L_LL.csv')
  # nse_stock = [symbol + '.NS' for symbol in symbol_name_csv['Symbol']]
  nse_stock = ['JWL.NS', 'KMEW.NS'] #'KOPRAN.NS', 
  for ticker in nse_stock:
    data = yf.download(ticker, period='150d', interval='1d', progress=False) #1
    # Check if data is not empty and meets price condition
    if not data.empty and round(data['Close'].iloc[-1].item(),2) >= 100 and data['Volume'].iloc[-1].item() > 150000:
      data['09_ema'] = calculate_ema(data,9)
      data['20_ema'] = calculate_ema(data,20)
      data = data.tail(15).round(2)
      flagi = flag(data)
      df = pd.DataFrame(flagi)

      if not df.empty:
        all_results.append(df)

  # Move the return statements outside the loop
  if all_results:
    return pd.concat(all_results, ignore_index=True)
  else:
    return pd.DataFrame() # Return an empty DataFrame if no results

if __name__ == "__main__":
    stock = index()
